services:
  app:
    build: .
    container_name: aguaviva
    ports:
      - "5901:5901"  # Porta VNC para acessar a interface gráfica
    volumes:
      - ./runs/train:/home/docker/runs/train
      - ./videos:/home/docker/videos
      - ./assets:/home/docker/assets
    restart: unless-stopped
    environment:
      - DISPLAY=:1
    # Opcional: Definir limites de recursos
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2.0'
    #       memory: '4G'
