[project]
name = "aguaviva"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.10.0.84",
    "pyqt5>=5.15.11",
    "ultralytics>=8.2.98",
]
